language: csharp
mono: none
dotnet: 3.1
solution: ./lab1.1/myprog/myprog.sln 
before_install:
  - sudo apt-get -y install dotnet-sdk-3.1
script:
  - rm ./lab1.1/myprog/myprog.sln
  - cd ./lab1.1/myprog
  - dotnet test