language: csharp
mono: none
dotnet: 3.1
before_install:
  - sudo apt-get -y install dotnet-sdk-3.1 
script:
  - dotnet test ./lab1.2/myprog2
  - dotnet build ./lab1.2/myprog2
  - dotnet test ./lab1.1/myprog
  - dotnet build ./lab1.1/myprog
  - dotnet build ./lab2t1
  - dotnet build ./lab2t2
  - dotnet build ./lab2t3
  - dotnet test ./lab2t3
  - dotnet build ./lab2t5
  - dotnet build ./lad3t1
  - dotnet build ./lab3t2
  - dotnet build ./lab3t3
  - dotnet build ./lab4t1
  - dotnet test ./lab4t1
  - dotnet build ./lab4t2
  - dotnet build ./lab4t3
  - dotnet build ./lab5t1
  - dotnet build ./lab5t2
  - dotnet build ./lab5t3
  - dotnet test ./lab5t3
